sonar.projectKey=devops-reactjs-app
sonar.projectName=React App
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=node_modules/**

sonar.sourceEncoding=UTF-8

# Optional (coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Sonar server
sonar.host.url=http://localhost:9000
sonar.login=squ_69bcb91748190797a20c4bb306e7377fc4e3cfc2